### ISSUE TITLE
Do we need to keep hugging face cache even after having a model in custom node model folder?

### ISSUE THREAD

**Issue by RYG81** [zhongpei/Comfyui_image2prompt#10]
C:\Users\*****\.cache\huggingface\hub\models--vikhyatk--moondream1 (18+ GB)

Do we need to keep this folder? We already have models in model folder - 

D:\000AI\00ComfyUI\ComfyUI\custom_nodes\Comfyui_image2prompt\model\moondream1

Also does anything run or stored in memory? even when comfyui not using the node?
thanks in advance

**Comment by zhongpei** [comment]
You can refer to here https://huggingface.co/docs/huggingface_hub/guides/manage-cache#limitations
