### ISSUE TITLE
 vision.pt does not exist

### ISSUE THREAD

**Issue by LeonidTheGod2** [zhongpei/Comfyui_image2prompt#11]
![image](https://github.com/zhongpei/Comfyui_image2prompt/assets/152413267/a9f857ef-a415-496a-b91c-d9dcb5ce6f08)

It says that vision.pt does not exist, but i have it. How can i fix it? Running on colab

ValueError: The provided filename /content/drive/MyDrive/ComfyUI/custom_nodes/Comfyui_image2prompt/model/moondream1/vision.pt does not exist

![image](https://github.com/zhongpei/Comfyui_image2prompt/assets/152413267/2915e847-6189-4ac3-89f0-a2715d07062d)

**Comment by zhongpei** [comment]
try dowanload this model again.
