### ISSUE TITLE
intemlm-xcomposer2 - error when running - can't move a model...

### ISSUE THREAD

**Issue by alenknight** [zhongpei/Comfyui_image2prompt#22]
getting this error when trying to run intemlm-xcompser2

![image](https://github.com/zhongpei/Comfyui_image2prompt/assets/22153900/79432b5d-c0d2-44fd-8ae4-d732b6d76e11)

**Comment by zhongpei** [comment]
This model does not occupy too much video memory due to quantification. It is recommended to use deepspeed-1.3B.
