### ISSUE TITLE
Import failed error

### ISSUE THREAD

**Issue by villain535** [zhongpei/Comfyui_image2prompt#23]
Installing your node on fresh PC with fresh ComfyUI from VastAI and always getting:

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): /opt/ComfyUI/custom_nodes/Comfyui_image2prompt

And comfyUI manager says that node installed with errors. 

Reinstall doesn’t fix that. 

What do I miss?

**Comment by zhongpei** [comment]
try update this node
