### ISSUE TITLE
Feature Request: Store models in ComfyUI/models

### ISSUE THREAD

**Issue by RedDeltas** [zhongpei/Comfyui_image2prompt#26]
It would be great if the model path could be moved from being inside the custom node to the `ComfyUI/models` path maybe in an `image2promt` directory?

This would be more inline with ComfyUIs principles, for me I use RunPod and I have different policies around what gets backed up - so anything in the `custom_nodes` directory will get backed up and this includes the large model files which I'd like to avoid.

**Comment by zhongpei** [comment]
huggingface download model just a link ,so you can copy the dir to anywhere

**Comment by RedDeltas** [comment]
Doesn't this node look in `ComfyUI/custom_nodes/Comfyui_image2prompt/model` to find the models though? I'm suggesting that it would be great if it loaded models from `ComfyUI/models/image2prompt` instead

**Comment by zhongpei** [comment]
please update and  move comfyui_image2text/model to comfyui/models/image2text

**Comment by RedDeltas** [comment]
Thank you 🙏
