### ISSUE TITLE
Cannot import name 'ToImage'

### ISSUE THREAD

**Issue by sblorg77** [zhongpei/Comfyui_image2prompt#3]
I *really* would like to use this, but are there any requirements for Torch? Maybe there is something missing in my setup, but I'm getting a message "cannot import name ToImage from torchvision.transforms.v2" with Torchvision 0.15.2 (sadly, I'm stuck with the old cu118 portable version of ComfyUI).

**Comment by zhongpei** [comment]
try this version 
```
pip install torchvision==0.16.0
```

**Comment by jmilez** [comment]
I tried the upgrade to 0.16.0 and still get the op's error. during install got this error message...

Installing collected packages: torch, torchvision
  Attempting uninstall: torch
    Found existing installation: torch 2.0.1+cu118
    Uninstalling torch-2.0.1+cu118:
      Successfully uninstalled torch-2.0.1+cu118
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.15.2+cu118
    Uninstalling torchvision-0.15.2+cu118:
      Successfully uninstalled torchvision-0.15.2+cu118

**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.21 requires torch==2.0.1, but you have torch 2.1.0 which is incompatible.
torchaudio 2.0.2+cu118 requires torch==2.0.1, but you have torch 2.1.0 which is incompatible.**

Successfully installed torch-2.1.0 torchvision-0.16.0

**Comment by proteus2000** [comment]
same problem here
