### ISSUE TITLE
这是认真的吗？

### ISSUE THREAD

**Issue by xavierzz** [zhongpei/Comfyui_image2prompt#36]
![Screenshot 2024-03-15 110139](https://github.com/zhongpei/Comfyui_image2prompt/assets/21898282/33cca958-7192-4536-a1c2-824b0913feb1)
这是认真的吗？

**Comment by xavierzz** [comment]
看了代码 为啥全是==？

**Comment by amimi818** [comment]
把我的transformers也给降级了

**Comment by zhongpei** [comment]
moondream1 need 4.37.1
