### ISSUE TITLE
建议：大家以后把用到的模型全部默认放到models目录里

### ISSUE THREAD

**Issue by aomiks** [zhongpei/Comfyui_image2prompt#38]
很多模型是其他节点也使用的，建议大家以后把用到的模型全部默认放到models目录里，大家要有环保意识，尤其模型文件本就较大，复制几份不是个好的办法，修改调用路径更新又变回去了，大家为何不统一默认放到models目录下呢？按照模型作者分类二级目录及多级目录。

**Comment by zhongpei** [comment]
please update and  move comfyui_image2text/model to comfyui/models/image2text
