### ISSUE TITLE
internlm-xcomposer2-vl-7b + CPU = Error

### ISSUE THREAD

**Issue by BenderBlender** [zhongpei/Comfyui_image2prompt#4]
Everything else works fine, but this combination throws an error (I would like to use the CPU sometimes, because CUDA conflicts with some nodes)

![image](https://github.com/zhongpei/Comfyui_image2prompt/assets/116355906/580b415f-a276-420f-ba80-378deb299981)

**Comment by zhongpei** [comment]
now fix it
