### ISSUE TITLE
依赖版本报错重复，无法解决

### ISSUE THREAD

**Issue by mmacheng** [zhongpei/Comfyui_image2prompt#44]
第一次安装之后，提示'sentencepiece==0.1.99'不满足 'sentencepiece==0.2.0'
手动安装0.2.0版本之后又提示如下：
C:\Users\MaCheng>pip install sentencepiece==0.2.0
Collecting sentencepiece==0.2.0
  Using cached sentencepiece-0.2.0-cp310-cp310-win_amd64.whl.metadata (8.3 kB)
Using cached sentencepiece-0.2.0-cp310-cp310-win_amd64.whl (991 kB)
Installing collected packages: sentencepiece
  Attempting uninstall: sentencepiece
    Found existing installation: sentencepiece 0.1.99
    Uninstalling sentencepiece-0.1.99:
      Successfully uninstalled sentencepiece-0.1.99
  WARNING: Failed to remove contents in a temporary directory 'D:\AITools\ComfyUI-aki-v1.1\python\Lib\site-packages\~--tencepiece'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
argostranslate 1.9.3 requires sentencepiece==0.1.99, but you have sentencepiece 0.2.0 which is incompatible.
deepseek-vl 1.0.0 requires transformers>=4.38.2, but you have transformers 4.37.1 which is incompatible.
Successfully installed sentencepiece-0.2.0
打开comfyui之后就又会自动装回 0.1.99版本。又开始重复前面得错误。
<img width="1853" alt="企业微信截图_20240322175916" src="https://github.com/zhongpei/Comfyui_image2prompt/assets/88197887/87e800d8-3814-468d-9df6-cb7e905f6cee">
![image](https://github.com/zhongpei/Comfyui_image2prompt/assets/88197887/86d0b09e-d7ba-4b9e-bf68-29dd97f2273b)

**Comment by zhongpei** [comment]
其他模型估计有冲突，不过应该不影响这个node的使用

**Comment by mmacheng** [comment]
> 其他模型估计有冲突，不过应该不影响该节点的使用

好的，非常感谢，只要不影响使用就行。
